myProjectBlog/urls.py
from django.contrib import admin
from django.urls import path
from myAppBlog.views import index, detallePost

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('<int:idPost>/', detallePost, name='detallePost')
]

myAppBlog/models.py
from django.db import models

class Post(models.Model):

    idPost = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=100)
    slug = models.SlugField()
    fecha = models.DateTimeField(auto_now_add=True)
    contenido = models.TextField()

    class Meta:

        verbose_name = "Post"
        verbose_name_plural = "Posts"
        db_table = "Posts"

    def __str__(self):

        return self.titulo 
    
class Comentarios(models.Model):

    idComentario = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    fecha = models.DateTimeField(auto_now_add=True)
    contenido = models.TextField()
    activo = models.BooleanField(default=True)
    fkPost = models.ForeignKey(Post, on_delete = models.CASCADE, related_name="comentarios")

    class Meta:

        verbose_name = "Comentario"
        verbose_name_plural = "Comentarios"
        db_table = "Comentarios"

    def __str__(self):

        return self.nombre

myAppBlog/forms.py
from django import forms
from .models import Comentarios

class FormularioComentarios(forms.ModelForm):
    class Meta:
        model = Comentarios
        fields = ['nombre', 'email', 'contenido', 'activo', 'fkPost']

myAppBlog/views.py
from django.shortcuts import render, redirect
from .models import Post, Comentarios
from .forms import FormularioComentarios

def index(request):

    posts = Post.objects.all()

    return render(request, 'index.html', {'posts': posts})


def detallePost(request, idPost):

    hola = Comentarios.objects.all()

    posts = Post.objects.get(idPost=idPost)

    if request.method == 'POST':

        form = FormularioComentarios(request.POST)

        if form.is_valid():

            nom = form.cleaned_data.get('nombre')
            em = form.cleaned_data.get('email')
            con = form.cleaned_data.get('contenido')
            act = form.cleaned_data.get('activo')
            fk = form.cleaned_data.get('fkPost')


            comentarios = Comentarios.objects.create(
            
                nombre = nom,
                email = em,
                contenido = con,
                activo = act,
                fkPost = fk,

            )

            comentarios.save()
            form = FormularioComentarios()
            
            

    else:

        form = FormularioComentarios()

    modulos = {'posts': posts, 'form': form, 'hola': hola}

    return render(request, 'detallePost.html', modulos)

myAppBlog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style type="text/tailwindcss">
        @layer utilities {
          body {
            background: black;
          }

          .hv1 {
            transition: .4s;
          }

          .hv1:hover {
            transform: scale(1.07);
          }

          .hv2 {
            transition: .4s;
          }

          .hv2:hover {
            text-decoration: overline #fefefe;
            transform: scale(1.07);
          }
        }
      </style>
</head>
<body>
    
    <nav class="navbar navbar-expand-lg bg-indigo-900">
        <div class="container-fluid">
          <a class="navbar-brand text-4xl text-white" href="/">Blog</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link text-white hv2" aria-current="page" href="#"></a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {% block content %}
      {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
</body>
</html>

myAppBlog/templates/detallePost.html
{% extends 'base.html'%}
{% load static %}



{% block content %}

    <h1 class="text-white text-4xl container p-8">Descripcion Posts</h1>

    <div class="container p-8">
        <h4 class="text-white text-2xl">{{posts.titulo}}</h4>
        <p class="text-white text-xl">{{posts.contenido}}</p>
        <p class="text-white text-lg">{{posts.fecha}}</p>
        <a href="/"><button class="m-6 middle none center rounded-lg bg-red-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-red-500/20 transition-all hover:shadow-lg hover:shadow-red-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" data-ripple-light="true">Regresar Post</button></a>

    </div>


    <div class="container text-white p-4">

        <h1 class="text-4xl mb-4">Formulario Post</h1>

        <form action="" method="POST">

            {% csrf_token %}
    
            <p>
                <label for="id_nombre" class="text-white text-xl">Nombre:</label>
                <input type="text" name="nombre" maxlength="100" required="" id="id_nombre" class="bg-black text-white border-2 border-red-800 rounded-lg mb-2">   
            </p>
    
            <p>
                <label for="id_email" class="text-white text-xl">Email:</label>
                <input type="email" name="email" maxlength="254" required="" id="id_email" class="bg-black text-white border-2 border-red-800 rounded-lg mb-2">
            </p>
    
            <p>
                <label for="id_contenido" class="text-white text-xl">Contenido:</label>
                <textarea name="contenido" cols="40" rows="10" required="" id="id_contenido" class="bg-black text-white border-2 border-red-800 rounded-lg"></textarea>
            </p>
    
            <p>
                <input type="hidden" name="activo" id="id_activo" readonly="True" value=1>
            </p>
    
            <p>
                <input type="hidden" name="fkPost" required="" id="id_fkPost" value="{{posts.idPost}}" readonly="True">  
            </p>
    
            <button type="submit" class="m-6 middle none center rounded-lg bg-red-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-red-500/20 transition-all hover:shadow-lg hover:shadow-red-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" data-ripple-light="true">Enviar comentario</button>
    
        </form>

    </div>
    
    <div class="container">
        <h2 class="text-white text-4xl container p-8">Comentarios Post</h2>
    </div>
    
    <div class="mx-10">

        {% for comentario in hola %}

        {% if comentario.fkPost_id == posts.idPost %}

        {% if comentario.activo == True %}
        
        <p class="text-white text-2xl mb-2">{{comentario.nombre}}</p>
        <p class="text-white text-sm mb-2">{{comentario.contenido}}</p>
        <p class="text-white text-xs mb-4">{{comentario.fecha}}</p>

        {% endif %}

        {% endif %}
        
        {% endfor %}

    </div>
    

{% endblock %}

myAppBlog/templates/index.html
{% extends 'base.html'%}
{% load static %}



{% block content %}

    <div class="container">

        <h1 class="text-white text-4xl p-10">Posts</h1>

        <img src="{% static 'django.jpg' %}" class="h-56">

            <div class="container p-4">
                {% for post in posts %}

                
                    <h2 class="text-white text-2xl p-2 flex">{{post.titulo}}</h2>
                    <a href="{% url 'detallePost' post.idPost %}"><button class="m-6 middle none center rounded-lg bg-red-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-red-500/20 transition-all hover:shadow-lg hover:shadow-red-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none" data-ripple-light="true">Ver Post</button></a>
                    
                
                
                {% endfor %}

            </div>
    </div>
    

{% endblock %}